baseURL = 'https://sam5124.github.io/zjjniubo1/'
languageCode = 'en-us'
publishDir="docs"
theme = 'ananke'
title = '生日快乐'
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

